name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'weather-docs/**'
      - '.github/workflows/docs.yml'

# Setzt Berechtigungen für GitHub Actions, um auf gh-pages zu pushen
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wichtig für mkdocs git-hooks

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        working-directory: ./weather-docs
